import asyncio
import logging
import time
from typing import Any

from langchain_core.messages import HumanMessage
from langchain_core.runnables import RunnableConfig
from langsmith import traceable

from backend.graph.sql_graph import sql_graph
from backend.nodes.market_node import run_market_retrieval
from backend.retrieval.query_filters import (
    extract_filters,
    generate_ranking_keywords
)
from backend.retrieval.vector_search import search_similar_chunks
from backend.observability.tracing import node_span
from backend.scoring.evidence_builder import extract_sql_rows

logger = logging.getLogger(__name__)

# timeouts per service
SQL_TIMEOUT    = 45  # seconds
VECTOR_TIMEOUT = 10  # seconds
MARKET_TIMEOUT = 8   # seconds


# ── Intent to retrieval path mapping ──────────────────────
SQL_INTENTS    = ["VALUATION", "GROWTH"]
VECTOR_INTENTS = ["SENTIMENT"]
MIXED_INTENTS  = ["MIXED"]


SQL_TOOL_NAMES = {
    "get_database_schema",
    "generate_sql_query",
    "execute_sql_query",
    "fix_sql_error",
}

# ── SQL Retrieval ───────────────────────────────────────────

@traceable(
    name="sql_retrieval",
    run_type="chain",
    tags=["retrieval", "sql"],
)
async def run_sql_retrieval(
    query: str,
    config: RunnableConfig,
    sql_question: str | None = None,
) -> dict[str, Any]:
    """
    Run SQL retrieval using the existing sql_graph.
    Returns structured results with confidence score.

    `sql_question` is the exact wording the SQL tools should be asked, and
    it is kept separate from `query` on purpose. `query` is the planner's
    subquery — keyword-shaped, written to steer retrieval — while the SQL
    generator needs the constraints the user actually stated, such as how
    many rows they asked for. Defaults to `query` when the caller has
    nothing better, which is the previous behaviour.
    """
    try:
        result = await sql_graph.ainvoke({
            "messages":          [HumanMessage(content=query)],
            "retry_count":       0,
            'original_question': '',
            'sql_question': sql_question or query,
            'last_sql': '',
            'db_result': {},
            'sql_executed_tools': []
        },
        config=config,)

        messages = result.get("messages", [])

        answer = (
            messages[-1].content
            if messages
            else ""
        )

        # SQL generated by the SQL graph
        generated_sql = result.get(
            "last_sql",
            "",
        )

        # SQL execution result
        db_result = result.get("db_result",{},)

        # SQL tools executed
        sql_executed_tools: list[str] = result.get("sql_executed_tools",[])


        confidence = 0.9 if "No companies" not in answer else 0.1
        
        logger.info("[HYBRID] SQL retrieval complete")
        return {
            "source":     "sql",
            "answer":     answer,
            "confidence": confidence,
            "generated_sql": generated_sql,
            "db_result": db_result,
            "sql_executed_tools": sql_executed_tools,
        }

    except Exception as e:
        logger.error(f"[HYBRID] SQL retrieval failed: {e}")
        return {
            "source":     "sql",
            "answer":     "",
            "confidence": 0.0,
            "generated_sql": "",
            "db_result": {},
            "sql_executed_tools": [],
            "error":      str(e),
            # The exception class, kept alongside the message so the SQL
            # boundary can log a short, low-cardinality label. Database
            # error *messages* can carry connection details, so they are
            # not what gets logged there.
            "error_type": type(e).__name__,
        }


# ── Vector Retrieval ────────────────────────────────────────

@traceable(
    name="vector_retrieval",
    run_type="chain",
    tags=["retrieval", "vector"],
)
async def run_vector_retrieval(
    query: str,
    config: RunnableConfig,
    top_k: int = 5,
    candidate_company_ids: list[int] | None = None,
) -> dict:
    """
    Run vector retrieval pipeline:
    1. Extract metadata filters from query
    2. Generate ranking keywords from query
    3. pgvector cosine similarity search with filters
    4. BM25 reranking by keyword relevance
    Returns structured result with confidence score.

    `candidate_company_ids` restricts the search to documents belonging to
    the eligible companies. Without it, retrieval for an AI question spent
    its five slots on Intel, Nike and a pharmaceutical upgrade — none of
    which belonged to any company being ranked, so relevance and sentiment
    were unmeasurable for every candidate.
    """
    try:
        filters  = await extract_filters(query,config)
        keywords = await generate_ranking_keywords(query,config)

        if candidate_company_ids:
            # Overrides any company the filter extractor inferred from the
            # wording: the candidate set was resolved from a curated
            # taxonomy and is the more reliable of the two.
            filters = {
                **(filters or {}),
                "company_ids": list(candidate_company_ids),
            }

        logger.info(
            f"[VECTOR] Vector filters: {filters}, "
            f"keywords: {keywords}"
        )

        rows = await search_similar_chunks(
            query    = query,
            top_k    = top_k,
            filters  = filters,
            keywords = keywords
        )

        if not rows:
            return {
                "source":     "vector",
                "retrieved_chunks":     [],
                "retrieved_contexts": [],
                "confidence": 0.0
            }

        retrieved_chunks = [{
            "chunk_id": row.id,
            "document_id": row.document_id,
            "content":     row.content[:600],
            "doc_type":    row.doc_type,
            "source":      row.source,
            "company_id":  row.company_id,
            "chunk_index": row.chunk_index,
            "similarity":  round(row.similarity, 3)
        } for row in rows]

        retrieved_contexts = [
            chunk["content"]
            for chunk in retrieved_chunks
        ]

        confidence = 0.8 if retrieved_chunks else 0.0

        logger.info(
            f"[HYBRID] Vector complete. "
            f"{len(retrieved_chunks)} chunks found"
        )

        return {
            "source": "vector",
            "retrieved_chunks": retrieved_chunks,
            "retrieved_contexts": retrieved_contexts,
            "confidence": confidence,
        }

    except Exception as exc:
        logger.error(f"[HYBRID] Vector retrieval failed: {exc}")
        return {
            "source": "vector",
            "retrieved_chunks": [],
            "retrieved_contexts": [],
            "confidence": 0.0,
            "error": str(exc),
        }

# ── Async Wrappers with Timeouts ────────────────────────────

@traceable(
    name="branch_sql",
    run_type="chain",
    tags=["retrieval", "sql", "branch"],
)
@node_span("sql")
async def run_sql_retrieval_async(
    query: str,
    config: RunnableConfig,
    sql_question: str | None = None,
) -> dict:
    """
    Async SQL retrieval with timeout.

    This function is the semantic SQL boundary: it is the last place that
    knows whether SQL retrieval actually produced usable rows. It keeps
    returning an error payload rather than raising, so a SQL failure still
    leaves vector and market retrieval to complete — which means the
    surrounding `node_span("sql")` correctly reports `ok` even when SQL did
    not succeed. The `[SQL] retrieval` lines below carry that distinction,
    since a span status alone cannot.
    """
    started = time.perf_counter()

    def elapsed_ms() -> float:
        return (time.perf_counter() - started) * 1000

    logger.info("[SQL] retrieval -> start")

    try:
        # run_sql_retrieval is a coroutine — awaiting it directly keeps
        # the LangSmith run context (a contextvar) attached. Handing it
        # to run_in_executor would return the un-awaited coroutine and
        # detach the trace.
        result = await asyncio.wait_for(
            run_sql_retrieval(
                query,
                config,
                sql_question=sql_question,
            ),
            timeout=SQL_TIMEOUT
        )

    except asyncio.TimeoutError:
        # Not an error for the pipeline — retrieval degrades and continues —
        # so this is a warning, and there is no traceback worth printing for
        # a timeout.
        logger.warning(
            "[SQL] retrieval <- timeout %.0fms timeout_ms=%d",
            elapsed_ms(),
            SQL_TIMEOUT * 1000,
        )
        return {
            "source": "sql",
            "answer": "",
            "confidence": 0.0,
            "error": "timeout"
        }

    except Exception as e:
        # The only place this exception is seen, so it keeps its traceback.
        logger.error(
            "[SQL] retrieval <- failed %.0fms error=%s",
            elapsed_ms(),
            type(e).__name__,
            exc_info=True,
        )
        return {
            "source": "sql",
            "answer": "",
            "confidence": 0.0,
            "error": str(e)
        }

    # A failure inside run_sql_retrieval was already converted into an error
    # payload there, so it arrives as a normal return. Without this check the
    # boundary would report `ok` for a run that retrieved nothing.
    if result.get("error"):
        # Already logged with its message one level down; a concise status is
        # enough here, and the class name avoids putting a driver's error
        # text — which can include connection details — on this line.
        logger.warning(
            "[SQL] retrieval <- failed %.0fms error=%s",
            elapsed_ms(),
            result.get("error_type") or "SQLRetrievalError",
        )
        return result

    logger.info(
        "[SQL] retrieval <- ok %.0fms rows=%d",
        elapsed_ms(),
        len(extract_sql_rows(result.get("db_result"))),
    )
    return result
    

@traceable(
    name="branch_vector",
    run_type="chain",
    tags=["retrieval", "vector", "branch"],
)
@node_span("vector")
async def run_vector_retrieval_async(
    query: str,
    config: RunnableConfig,
    candidate_company_ids: list[int] | None = None,
) -> dict:
    """Async vector retrieval with timeout."""
    try:
        logger.info("[HYBRID] Vector task started")

        result = await asyncio.wait_for(
             run_vector_retrieval(
                 query,
                 config,
                 candidate_company_ids=candidate_company_ids,
             ),
            timeout=VECTOR_TIMEOUT
        )

        logger.info("[HYBRID] Vector task complete")
        return result
    except asyncio.TimeoutError:
        logger.error(f"[HYBRID] Vector timed out after {VECTOR_TIMEOUT}s")
        return {
            "source":             "vector",
            "retrieved_chunks":   [],
            "retrieved_contexts": [],
            "confidence":         0.0,
            "error":              "timeout"
        }
    except Exception as e:
        logger.error(f"[HYBRID] Vector async failed: {e}", exc_info=True)
        return {
            "source":             "vector",
            "retrieved_chunks":   [],
            "retrieved_contexts": [],
            "confidence":         0.0,
            "error":              str(e)
        }


@traceable(
    name="branch_market",
    run_type="chain",
    tags=["retrieval", "market", "branch"],
)
@node_span("market")
async def run_market_retrieval_async(market_query: str,config:RunnableConfig) -> dict:
    """Async market retrieval with timeout."""
    try:
        logger.info("[HYBRID] Market task started")

        result = await asyncio.wait_for(
            run_market_retrieval(
                market_query,
                config,
            ),
            timeout=MARKET_TIMEOUT,
        )

        logger.info("[HYBRID] Market task complete")
        return result
    except asyncio.TimeoutError:
        logger.error(f"[HYBRID] Market timed out after {MARKET_TIMEOUT}s")
        return {
            "source":     "market",
            "market_data": {},
            "confidence": 0.0,
            "error":      "timeout"
        }
    except Exception as e:
        logger.error(f"[HYBRID] Market async failed: {e}", exc_info=True)
        return {
            "source":     "market",
            "market_data": {},
            "confidence": 0.0,
            "error":      str(e)
        }

# ── Dynamic Weight Calculator ───────────────────────────────

@traceable(
    name="calculate_weights",
    run_type="chain",
    tags=["scoring", "weights"],
)
def calculate_weights(
    intent:        str,
    market_result: dict = None
) -> dict:
    """
    Calculate confidence weights dynamically.
    Adjusts market weight to 0 if market data unavailable.
    Redistributes weight to SQL and Vector.
    """
    market_available = (
        market_result is not None and
        market_result.get("confidence", 0.0) > 0
    )

    if intent in SQL_INTENTS:
        return {"sql": 1.0, "vector": 0.0, "market": 0.0}

    elif intent in VECTOR_INTENTS:
        return {"sql": 0.0, "vector": 1.0, "market": 0.0}

    else:  # MIXED
        if market_available:
            return {"sql": 0.4, "vector": 0.3, "market": 0.3}
        else:
            # market unavailable — redistribute its weight
            return {"sql": 0.6, "vector": 0.4, "market": 0.0}





# ── Combine Results ─────────────────────────────────────────

@traceable(
    name="combine_results",
    run_type="chain",
    tags=["scoring", "fanin"],
)
def combine_results(
    query:         str,
    intent:        str,
    sql_result:    dict = None,
    vector_result: dict = None,
    market_result: dict = None
) -> dict:
    """
    Combine retrieval results into unified response.
    Adjusts weights when market data unavailable.
    Weights per intent:
    VALUATION → SQL 100%
    GROWTH    → SQL 100%
    SENTIMENT → Vector 100%
    MIXED     → SQL 40% + Vector 30% + Market 30%
    """

    sql_r    = sql_result    or {"confidence": 0.0}
    vector_r = vector_result or {"confidence": 0.0}
    market_r = market_result or {"confidence": 0.0}

    weights = calculate_weights(intent, market_result)

    overall_confidence = round(
        (sql_r["confidence"]    * weights["sql"])    +
        (vector_r["confidence"] * weights["vector"]) +
        (market_r["confidence"] * weights["market"]),
        3
    )

    result = {
        "query":              query,
        "intent":             intent,
        "overall_confidence": overall_confidence,
        "weights_used":       weights
    }

    if sql_result:
        result["sql_result"] = {
            "answer":     sql_result["answer"],
            "confidence": sql_result["confidence"],
            # Rows and SQL are what the hybrid reranker scores as
            # SQL evidence; dropping them here leaves it with nothing.
            "db_result":     sql_result.get("db_result", {}),
            "generated_sql": sql_result.get("generated_sql", ""),
            "error":      sql_result.get("error")
        }

    if vector_result:
        result["vector_result"] = {
            "retrieved_chunks":   vector_result["retrieved_chunks"],
            "retrieved_contexts": vector_result.get(
                "retrieved_contexts", []
            ),
            "confidence": vector_result["confidence"],
            "error":      vector_result.get("error")
        }

    if market_result:
        result["market_result"] = {
            "market_data": market_result["market_data"],
            "confidence": market_result["confidence"],
            "cached":     market_result.get("cached", False),
            "stale":      market_result.get("stale", False),
            "degraded":   market_result.get("degraded", False),
            "error":      market_result.get("error")
        }

    
    return result




# ── Main Async Hybrid Function ────────────────────────────────────

@traceable(
    name="hybrid_retrieval",
    run_type="chain",
    tags=["retrieval", "fanout"],
)
async def hybrid_retrieve_async(
    query:        str,
    intent:       str,
    sql_query:    str = None,
    vector_query: str = None,
    market_query: str = None,
    config: RunnableConfig | None = None,
    candidate_tickers: list[str] | None = None,
    candidate_company_ids: list[int] | None = None,
) -> dict:
    """
    Production-grade async hybrid retrieval.

    Features:
    - Fan-out/fan-in with asyncio.gather
    - Per-service timeouts
    - Partial results on failure
    - Dynamic weight adjustment
    - Full exception logging

    Routes:
    VALUATION → SQL only
    GROWTH    → SQL only
    SENTIMENT → Vector only
    MIXED     → SQL + Vector + Market in parallel
    """
    sql_q    = sql_query    or query
    vector_q = vector_query or query
    market_q = market_query or ""

    # The wording the SQL generator is asked, as opposed to `sql_q`, which
    # steers retrieval. The planner rewrites the question into a keyword
    # subquery — "technology companies low PE ratio undervalued market cap" —
    # which is right for search and wrong for SQL generation, because the
    # constraints the user stated do not survive it. A question asking for
    # five companies becomes one asking for none, and the generator then
    # defaults to LIMIT 10.
    #
    # SQL-only intents therefore ask the user's own question, which is
    # entirely about the metrics SQL owns. MIXED keeps the planner's subquery,
    # because there the full question also covers news and market data that
    # SQL cannot answer, and handing all of it to the SQL generator would be
    # worse than losing the count.
    sql_question = query if intent in SQL_INTENTS else sql_q

    candidate_tickers = candidate_tickers or []
    candidate_company_ids = candidate_company_ids or []

    # One eligible set for every branch. Previously each discovered its own:
    # SQL manufactured a filter from document text and returned EOG/JPM/GS
    # while the market branch resolved NVDA/MSFT/GOOGL/AMZN/META from the
    # planner's wording, and the scorer ranked the union of the two.
    if candidate_tickers:
        # Stated as a constraint on the question rather than by editing the
        # generated SQL: the generator already has a rule for honouring an
        # explicit ticker list, and rewriting its output would mean parsing
        # SQL to find the right place to intervene.
        sql_question = (
            f"{sql_question}\n\n"
            "Restrict the results to exactly these companies, which have "
            "already been determined to match the category the question "
            f"asks about: {', '.join(candidate_tickers)}. "
            "Filter with c.ticker IN (...) and do not widen the set."
        )

        # The market branch resolves tickers from free text with an LLM
        # call. Given the candidates it does not need to guess, and cannot
        # drift onto a different set — it previously answered a question
        # about AMD with AMZN.
        market_q = ", ".join(candidate_tickers)

    logger.info(
        f"[HYBRID] Intent: {intent}, "
        f"sql_q: {sql_q[:50]}, "
        f"vector_q: {vector_q[:50]}, "
        f"market_q: {market_q[:50]}, "
        f"candidates: {','.join(candidate_tickers) or 'all'}"
    )

    if intent in SQL_INTENTS:
        # VALUATION or GROWTH → SQL only
        sql_result = await run_sql_retrieval(
            sql_q,
            config,
            sql_question=sql_question,
        )
        return combine_results(
            query      = query,
            intent     = intent,
            sql_result = sql_result
        )

    elif intent in VECTOR_INTENTS:
        # SENTIMENT → Vector only
        vector_result = await run_vector_retrieval(
            vector_q,
            config,
            candidate_company_ids=candidate_company_ids,
        )
        return combine_results(
            query         = query,
            intent        = intent,
            vector_result = vector_result
        )

    else:
        # MIXED → SQL + Vector + Market API
        # MIXED — fan-out all tasks in parallel with timeout
        logger.info(
            "[HYBRID_ASYNC] Fanning out 3 tasks in parallel"
        )

        tasks = [
            run_sql_retrieval_async(
                sql_q,
                config,
                sql_question=sql_question,
            ),
            run_vector_retrieval_async(
                vector_q,
                config,
                candidate_company_ids=candidate_company_ids,
            ),
        ]

        if market_q:
            tasks.append(run_market_retrieval_async(market_q,config))

        try:
            # fan-in with overall timeout
            
            results = await asyncio.wait_for(
                asyncio.gather(*tasks, return_exceptions=True),
                timeout=60
            ) 
            
            #sql_result = await run_sql_retrieval_async(sql_q)
            #vector_result = await run_vector_retrieval_async(vector_q)
            #market_result = await run_market_retrieval_async(market_q)
        except asyncio.TimeoutError:
            logger.error("[HYBRID_ASYNC] Overall timeout after 20s")
            results = [
                {"source": "sql",    "answer": "", "confidence": 0.0, "error": "timeout"},
                {"source": "vector", "chunks": [], "confidence": 0.0, "error": "timeout"},
            ]
        

        # extract results safely
        sql_result = results[0] if (
            len(results) > 0 and
            not isinstance(results[0], Exception)
        ) else {"source": "sql", "answer": "", "confidence": 0.0, "error": "failed"}

        vector_result = results[1] if (
            len(results) > 1 and
            not isinstance(results[1], Exception)
        ) else {"source": "vector", "chunks": [], "confidence": 0.0, "error": "failed"}

        market_result = results[2] if (
            len(results) > 2 and
            not isinstance(results[2], Exception)
        ) else None

        # log exceptions
        for i, r in enumerate(results):
            if isinstance(r, Exception):
                logger.error(
                    f"[HYBRID_ASYNC] Task {i} raised: {r}",
                    exc_info=r
                )

        logger.info(
            f"[HYBRID_ASYNC] Fan-in complete. "
            f"SQL: {sql_result.get('confidence', 0)}, "
            f"Vector: {vector_result.get('confidence', 0)}, "
            f"Market: {market_result.get('confidence', 0) if market_result else 'N/A'}"
        )

        return combine_results(
            query         = query,
            intent        = intent,
            sql_result    = sql_result,
            vector_result = vector_result,
            market_result = market_result
        )