"""add claim_evaluations

One row per factual claim per benchmark answer, with the evaluator's label
and a separate column a human writes.

WRITTEN BY HAND, NOT LEFT AS AUTOGENERATED
    --autogenerate produced this table and then eleven other operations
    from pre-existing drift between the models and the live schema: it
    would have dropped evaluation_metrics.overall_pass_rate and
    .route_accuracy, dropped the HNSW index on document_chunks added in
    ed2de6d3b0f7, and renamed six indexes. All of that is unrelated to
    claim auditing, and two of them lose data.

    That drift is real and worth fixing, but not silently, inside a
    migration whose message says it adds a table.

Revision ID: 7fda2e226bca
Revises: b9e41a7c0d52
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7fda2e226bca"
down_revision: Union[str, Sequence[str], None] = "b9e41a7c0d52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "claim_evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("question_id", sa.String(), nullable=False),
        sa.Column("route", sa.String(), nullable=True),
        sa.Column("claim_index", sa.Integer(), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("original", sa.Text(), nullable=True),
        sa.Column("is_numeric", sa.Boolean(), nullable=True),
        sa.Column("numeric_values", sa.JSON(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column("evaluator_label", sa.String(length=24), nullable=False),
        sa.Column("evaluator_reasoning", sa.Text(), nullable=True),
        sa.Column("evaluator_model", sa.String(), nullable=True),
        # Nullable and written only through the validation endpoint. A
        # re-run replaces evaluator_label and must leave this untouched,
        # or the two can no longer be compared.
        sa.Column("human_label", sa.String(length=24), nullable=True),
        sa.Column("human_labeled_by", sa.String(), nullable=True),
        sa.Column("human_labeled_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["benchmark_runs.run_id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id",
            "question_id",
            "claim_index",
            name="uq_claim_evaluations_run_question_index",
        ),
    )

    op.create_index(
        op.f("ix_claim_evaluations_id"), "claim_evaluations", ["id"]
    )
    op.create_index(
        op.f("ix_claim_evaluations_run_id"), "claim_evaluations", ["run_id"]
    )
    op.create_index(
        op.f("ix_claim_evaluations_question_id"),
        "claim_evaluations",
        ["question_id"],
    )
    op.create_index(
        op.f("ix_claim_evaluations_evaluator_label"),
        "claim_evaluations",
        ["evaluator_label"],
    )
    # The validation page's main query is "claims not yet labelled", which
    # is a scan of this column.
    op.create_index(
        op.f("ix_claim_evaluations_human_label"),
        "claim_evaluations",
        ["human_label"],
    )
    op.create_index(
        op.f("ix_claim_evaluations_is_numeric"),
        "claim_evaluations",
        ["is_numeric"],
    )


def downgrade() -> None:
    op.drop_table("claim_evaluations")
