"""drop alerts

The table has never had a writer. `Alert` is referenced nowhere outside
db_models.py -- no route reads it, no service inserts into it, and no
screen displays it. It described a threshold-breach alerting feature that
was never built.

WHY DROP RATHER THAN LEAVE IT

    An empty table is not free. It is schema that describes a system,
    and a reader who finds `alerts` reasonably concludes something
    generates alerts. Five other tables were in the same state; the
    others are being given writers, because per-query latency, cost and
    retrieval records are worth having. This one is not: there is no
    alerting path, no destination for an alert, and no plan to add one.

    Deleting a feature you decided against is a decision. Leaving an
    empty table is an unfinished sentence.

WRITTEN BY HAND, NOT AUTOGENERATED

    For the reason 7fda2e226bca gives: --autogenerate still produces
    unrelated operations from pre-existing drift between the models and
    the live schema, including dropping the HNSW index added in
    ed2de6d3b0f7. A migration whose message says it drops one table
    should drop one table.

The downgrade recreates it, so this is reversible if alerting is ever
built -- though at that point the schema should be designed for whatever
actually raises the alert, not restored from here.

Revision ID: c1d4a8e37b90
Revises: 7fda2e226bca
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c1d4a8e37b90"
down_revision: Union[str, Sequence[str], None] = "7fda2e226bca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_index("ix_alerts_id", table_name="alerts")
    op.drop_table("alerts")


def downgrade() -> None:
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("alert_type", sa.String(), nullable=True),
        sa.Column("threshold", sa.Float(), nullable=True),
        sa.Column("actual_value", sa.Float(), nullable=True),
        sa.Column("severity", sa.String(), nullable=True),
        sa.Column(
            "triggered_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["benchmark_runs.run_id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_alerts_id", "alerts", ["id"], unique=False)
